"""
One-time secret generation for the C2 server.

Run this before first launch:
    python setup_secrets.py

Writes all required secrets to server/.env with cryptographically
random values. Never commit .env to version control.
"""
import os
import secrets

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')

lines = [
    "# C2 Framework - Server Secrets",
    "# Generated by setup_secrets.py - DO NOT COMMIT",
    "",
    f"C2_API_KEY={os.urandom(32).hex()}",
    f"SECRET_KEY={os.urandom(32).hex()}",
    f"OPERATOR_KEY={os.urandom(32).hex()}",
    f"OPERATOR_USER=operator",
    f"OPERATOR_PASS={secrets.token_urlsafe(24)}",
    f"ENCRYPTION_KEY={os.urandom(32).hex()}",    # bootstrap AES key (ECDH replaces per-session)
    f"DB_ENCRYPTION_KEY={os.urandom(32).hex()}", # separate key for SQLite field encryption
    "",
    "ENCRYPT_BEACON=true",
]

with open(ENV_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"[+] Secrets written to: {ENV_PATH}")
print()
print("    OPERATOR_PASS is printed below — save it now:")
for line in lines:
    if line.startswith("OPERATOR_PASS="):
        print(f"    {line}")
print()
print("[!] Never commit .env to version control.")
print("[+] Next steps:")
print("    1. python gen_cert.py")
print("    2. python app.py")
